//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.READERS_INFO = new HashSet<READERS_INFO>();
            this.USERS = new HashSet<USER>();
        }
    
        public int REC_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual ICollection<READERS_INFO> READERS_INFO { get; set; }
        public virtual ICollection<USER> USERS { get; set; }
    }
}
