//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICTIONARY
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME_UZ { get; set; }
        public string NAME_RU { get; set; }
        public Nullable<int> DICTIONARY_TYPE_ID { get; set; }
        public Nullable<bool> IS_DEFAULT { get; set; }
        public Nullable<bool> IS_ARCHIVE { get; set; }
    }
}
