//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_REQUESTS
    {
        public long REC_ID { get; set; }
        public string REQ_TYPE { get; set; }
        public string REQ_MESSAGE { get; set; }
        public string RES_MESSAGE { get; set; }
        public Nullable<System.DateTime> REQ_DATETIME { get; set; }
        public Nullable<int> REQ_USER { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
