//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXED_INTERNAL_VALUES
    {
        public int PKM_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> VALUE { get; set; }
    }
}
