//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterView
    {
        public int REC_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string SURNAME_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public bool PRINTED { get; set; }
        public string ADDRESS { get; set; }
        public string CARD_NUMBER { get; set; }
        public string PIN { get; set; }
        public string TIN { get; set; }
        public string PICTURE_PATH { get; set; }
        public long CARD_ID { get; set; }
    }
}
