//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartCardDBEntities : DbContext
    {
        public SmartCardDBEntities()
            : base("name=SmartCardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUDIT> AUDITs { get; set; }
        public virtual DbSet<CARD_INFO> CARD_INFO { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DICTIONARY> DICTIONARies { get; set; }
        public virtual DbSet<DICTIONARY_TYPE> DICTIONARY_TYPE { get; set; }
        public virtual DbSet<EXTERNAL_REQUESTS> EXTERNAL_REQUESTS { get; set; }
        public virtual DbSet<FIXED_INTERNAL_VALUES> FIXED_INTERNAL_VALUES { get; set; }
        public virtual DbSet<READERS_INFO> READERS_INFO { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSEs { get; set; }
        public virtual DbSet<WAREHOUSE_DTL> WAREHOUSE_DTL { get; set; }
    }
}
