//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.CARD_INFO = new HashSet<CARD_INFO>();
            this.CARD_INFO1 = new HashSet<CARD_INFO>();
            this.EXTERNAL_REQUESTS = new HashSet<EXTERNAL_REQUESTS>();
            this.READERS_INFO = new HashSet<READERS_INFO>();
            this.READERS_INFO1 = new HashSet<READERS_INFO>();
            this.WAREHOUSE_DTL = new HashSet<WAREHOUSE_DTL>();
        }
    
        public int REC_ID { get; set; }
        public string LOGIN { get; set; }
        public byte[] PASSWORD { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> DEPARTMENT { get; set; }
        public string FIRST_NAME { get; set; }
        public string SURNAME_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string ADDRESS { get; set; }
        public string PASSPORT { get; set; }
        public string TIN { get; set; }
        public string PIN { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual ICollection<CARD_INFO> CARD_INFO { get; set; }
        public virtual ICollection<CARD_INFO> CARD_INFO1 { get; set; }
        public virtual DEPARTMENT DEPARTMENT1 { get; set; }
        public virtual ICollection<EXTERNAL_REQUESTS> EXTERNAL_REQUESTS { get; set; }
        public virtual ICollection<READERS_INFO> READERS_INFO { get; set; }
        public virtual ICollection<READERS_INFO> READERS_INFO1 { get; set; }
        public virtual ICollection<WAREHOUSE_DTL> WAREHOUSE_DTL { get; set; }
    }
}
