//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCardDesc.EntityModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE()
        {
            this.WAREHOUSE_DTL = new HashSet<WAREHOUSE_DTL>();
        }
    
        public int REC_ID { get; set; }
        public Nullable<System.DateTime> INPUT_DT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string ITEN_NAME { get; set; }
        public Nullable<int> INIT_QUANTITY { get; set; }
        public Nullable<decimal> REMAINING_AMOUNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE_DTL> WAREHOUSE_DTL { get; set; }
    }
}
